# ==============================
# 🖍️ Xoria256
# ==============================

# ==============================
# Background and Foreground
# ==============================
background           #000000
foreground           #d0d0d0
selection_background #d0d0d0
selection_foreground #0c0c0c
cursor               #d0d0d0
macos_titlebar_color #000000

# ==============================
# Tabs
# ==============================
active_tab_background   #d0d0d0
active_tab_foreground   #0c0c0c
inactive_tab_background #0c0c0c
inactive_tab_foreground #d0d0d0

# ==============================
# ANSI Colors (0–15)
# ==============================
color0  #0c0c0c
color1  #d78787
color2  #afd787
color3  #f7f7af
color4  #87afd7
color5  #d7afd7
color6  #afd7d7
color7  #e6e6e6

color8  #bababa
color9  #df8787
color10 #afdf87
color11 #ffffaf
color12 #87afdf
color13 #dfafdf
color14 #afdfdf
color15 #eeeeee