# ==============================
# 🌿 Catppuccin Mocha
# ==============================

# ==============================
# Background and Foreground
# ==============================
background           #1e1e2e
foreground           #cdd6f4
cursor               #f5e0dc
selection_background #45475a
selection_foreground #f5e0dc

# ==============================
# Tabs
# ==============================
active_tab_background   #cdd6f4
active_tab_foreground   #1e1e2e
inactive_tab_background #181825
inactive_tab_foreground #a6adc8

# ==============================
# ANSI Colors (0–15)
# ==============================
color0  #45475a
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #cba7f7
color6  #94e2d5
color7  #cdd6f4

color8  #585b70
color9  #eba0ac
color10 #b4f9c8
color11 #fab387
color12 #89b4fa
color13 #cba7f7
color14 #94e2d5
color15 #f2cdcd
