# ==============================
# 🌺 Catppuccin Macchiato
# ==============================

# ==============================
# Background and Foreground
# ==============================
background           #24273a
foreground           #cad3f5
selection_background #494d64
selection_foreground #f4dbd6
cursor               #f4dbd6
macos_titlebar_color #24273a

# ==============================
# Tabs
# ==============================
active_tab_background   #cad3f5
active_tab_foreground   #24273a
inactive_tab_background #1e2030
inactive_tab_foreground #a5adcb

# ==============================
# ANSI Colors (0-15)
# ==============================
color0  #5b6078
color1  #ed8796
color2  #a6da95
color3  #eed49f
color4  #8aadf4
color5  #c6a0f6
color6  #91d7e3
color7  #cad3f5

color8  #494d64
color9  #ee99a0
color10 #8bd5ca
color11 #f5a97f
color12 #7dc4e4
color13 #f5bde6
color14 #b7bdf8
color15 #a5adcb
