# ==============================
# 🪴 Catppuccin Frappé
# ==============================

# ==============================
# Background and Foreground
# ==============================
background           #303446
foreground           #c6d0f5
selection_background #51576d
selection_foreground #f2d5cf
cursor               #f2d5cf
macos_titlebar_color #303446

# ==============================
# Tabs
# ==============================
active_tab_background   #c6d0f5
active_tab_foreground   #303446
inactive_tab_background #292c3c
inactive_tab_foreground #a5adce

# ==============================
# ANSI Colors (0-15)
# ==============================
color0  #626880
color1  #e78284
color2  #a6d189
color3  #e5c890
color4  #8caaee
color5  #ca9ee6
color6  #99d1db
color7  #c6d0f5

color8  #51576d
color9  #ea999c
color10 #81c8be
color11 #ef9f76
color12 #85c1dc
color13 #f4b8e4
color14 #babbf1
color15 #a5adce
