#!/usr/bin/env sh

# ==============================
# Applications
# ==============================
alt - return : open -a  "Finder"
alt - k      : open -na "kitty"
alt - v      : open -a  "Visual Studio Code"
alt - s      : open -a  "Spotify"
alt - z      : open -a  "Zen"

# ==============================
# Yabai
# ==============================
    # focus
ctrl + alt - left  : /opt/homebrew/bin/yabai -m window --focus west
ctrl + alt - down  : /opt/homebrew/bin/yabai -m window --focus south
ctrl + alt - up    : /opt/homebrew/bin/yabai -m window --focus north
ctrl + alt - right : /opt/homebrew/bin/yabai -m window --focus east
    # rotation
ctrl + alt - r         : /opt/homebrew/bin/yabai -m space --rotate 270
ctrl + alt + shift - r : /opt/homebrew/bin/yabai -m space --rotate 90
    # misc
ctrl - f : /opt/homebrew/bin/yabai -m window --toggle float && /opt/homebrew/bin/yabai -m window --grid 4:4:1:1:2:2
ctrl - z : /opt/homebrew/bin/yabai -m window --toggle zoom-fullscreen
ctrl - o : /opt/homebrew/bin/yabai -m window --toggle split
ctrl - b : /opt/homebrew/bin/yabai -m space  --balance
