#!/usr/bin/env sh

# ==============================
# Main
# ==============================
sudo yabai --load-sa
yabai -m config layout bsp

# ==============================
# Windows - regular cases
# ==============================
yabai -m config top_padding    4
yabai -m config bottom_padding 4
yabai -m config left_padding   4
yabai -m config right_padding  4
yabai -m config window_gap     4

# ==============================
# Windows - special cases
# ==============================
yabai -m config --space 5 top_padding    10
yabai -m config --space 5 bottom_padding 24

# ==============================
# Mouse
# ==============================
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_drop_action swap

# ==============================
# Exceptions
# ==============================
yabai -m rule --add app="^Finder$"           manage=off
yabai -m rule --add app="^System Settings$"  manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Spotify$"          manage=off
yabai -m rule --add app="^Zen$"              manage=off
yabai -m rule --add app="^v2RayTun$"         manage=off
yabai -m rule --add title="Preferences$"     manage=off
yabai -m rule --add title="Settings$"        manage=off

# ==============================
# Window misc
# ==============================
yabai -m config window_placement first_child
yabai -m config window_shadow float

# ==============================
# Other misc
# ==============================
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
